# Generated by Django 4.0.4 on 2022-06-12 17:59

from django.db import migrations, models
import django_base64field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('image', django_base64field.fields.Base64Field(blank=True, default='', max_length=1000000, null=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentID', models.CharField(max_length=1000)),
                ('DocumentName', models.CharField(max_length=500)),
                ('DocumentDesc', models.TextField()),
                ('DocumentQuests', models.JSONField()),
                ('Creator', models.IntegerField()),
            ],
        ),
    ]
