# Generated by Django 4.0.4 on 2022-06-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocumentID', models.CharField(max_length=1000)),
                ('DocumentName', models.CharField(max_length=500)),
                ('DocumentDesc', models.TextField()),
                ('DocumentQuests', models.JSONField()),
            ],
        ),
    ]
